### PR TITLE
Conversion to Maven; serializable objects. 

### PR DESCRIPTION
**Pull request by ZenHarbinger**
I forked and converted the project to use maven (pom.xml).
I have also:
1. Separated out the cursor/object/blob listener functionality into separate inner classes.
2. TuioObject/Cursor/Blob are now serializable
3. Added get/set methods to allow [de]serialization using JSON (I personally use Jackson).
4. The OSC code is now pulled from maven using version 0.2 of the available artifacts.
5. Use of apache-commons logging and lang3 (for event handling).

I had particular interest in all of the serialization because of a project I am working on requires different methods of serializing for broadcasting the events to multiple clients.

I am currently pushing the library into the maven repositories, but thought I should let you have the option of pulling in the code to the upstream.

### CODE REVIEW

**Comment by mkalten** [comment]
Hi @ZenHarbinger, thanks for the request, but your changes are too heavy to be included into the mainline version at this point ... nevertheless I ported some of your bug fixes and the serialization.

BTW, I see that you re-licensed your fork from the the original LGPL, that's not possible IMHO.

**Comment by ZenHarbinger** [comment]
AH, ok, I'll fix that.

**Comment by ZenHarbinger** [comment]
Can you tell me where the license is changed?
my pom.xml LICENSE.TXT and licenseheader.txt are all LGPL.

**Comment by ZenHarbinger** [comment]
Figured it out, was a copy paste bug when separating out files I'm sure. Sorry about that.

**Comment by mkalten** [comment]
The LICENSE.TXT is still LGPL, but all the file headers are changed ...
edit: thanks for the quick fix ;)

**Pull request closed without merging**
